# Generated by Django 2.0 on 2018-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Name')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
    ]
