# Generated by Django 2.0 on 2018-01-23 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Ip Address')),
                ('start_datetime', models.DateTimeField(verbose_name='Start of Trip Time')),
                ('end_datetime', models.DateTimeField(verbose_name='Start of Trip Time')),
                ('duration', models.DurationField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collect.Route')),
            ],
        ),
    ]
